# -*- coding: utf-8 -*-
"""Moving Average Convergence Divergence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dY9hJVdFb4v9lVsyY39wCsDKWI3ZTBWv
"""

# Commented out IPython magic to ensure Python compatibility.
#Importando as Bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

#Comando para selecionar o arquivo gerado pelo programa de ETL
from google.colab import files
arquivo = files.upload()

#Leitura do arquivo Bobespa (Colocar aqui o nome do seu arquivo)
df = pd.read_csv('all_bovespa.csv', delimiter=',')

#Definindo a variável com o Ticker da ação desejada
df_itau = df[df['sigla_acao'] == 'ITUB4']

#Verificar os tipos
df_itau.dtypes

#Formatando a data
df_itau['data_pregao']=pd.to_datetime(df_itau['data_pregao'],format='%Y-%m-%d')

#Verificar os tipos
df_itau.dtypes

#Definindo o filtro de data
df_itau_2020=df_itau[df_itau['data_pregao']<='2021-01-01']

#Verificação do data frame
df_itau_2020

#Definindo data do pregao como índice
df_itau_2020=df_itau_2020.set_index(pd.DatetimeIndex(df_itau_2020['data_pregao'].values))

#Verificação do data frame
df_itau_2020

#Calculo médias móveis dos 12 dias (Rápida quantidade de dias reduzidos)
rapidaMME=df_itau_2020.preco_fechamento.ewm(span=12).mean()

#Calculo médias móveis 26 dias (Lenta quantidade de dias amplos)
lentaMME=df_itau_2020.preco_fechamento.ewm(span=26).mean()

#Calculo do MACD (Moving Average Convergence Divergence)
MACD=rapidaMME - lentaMME

#Calculo do sinal é a linha de gatilho para entrada e saída da ação com janela de 9 dias.
sinal=MACD.ewm(span=9).mean()

#Plotando Gráfico para visualização
plt.figure(figsize=(15,5))
plt.plot(df_itau_2020.index, MACD , label = 'Itau', color='blue')
plt.plot(df_itau_2020.index, sinal , label = 'sinal', color='orange')
plt.xticks(rotation=90)
plt.legend(loc='upper right')
plt.show()

#Inserindo MACD e sinal dentro do Data Frame
df_itau_2020['MACD'] = MACD
df_itau_2020['sinal'] = sinal
df_itau_2020

#Plotando gráfico com os valores da ação (Abertura, Máximo, Mínimo, Fechamento)

#Importando as bibliotecas
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots

#Definindo Mínimo e Máximo
minimo=min([min(df_itau_2020['sinal']),min(df_itau_2020['MACD'])])
maximo=max([max(df_itau_2020['sinal']),max(df_itau_2020['MACD'])])


#Criação de Sub Plots

#Candlestick
fig = make_subplots(vertical_spacing = 0, rows=2, cols=1, row_heights=[4,3])

fig.add_trace(go.Candlestick(x=df_itau_2020.index, open= df_itau_2020['preco_abertura'], high=df_itau_2020['preco_maximo'],
                          low=df_itau_2020['preco_minimo'], close= df_itau_2020['preco_fechamento']))

#Cálculo do MACD
fig.add_trace(go.Scatter(x=df_itau_2020.index, y = df_itau_2020['MACD'], name='MACD', line = dict(color='blue')), row=2, col=1)
fig.add_trace(go.Scatter(x=df_itau_2020.index, y = df_itau_2020['sinal'], name='Sinal', line = dict(color='yellow')), row=2, col=1)


#Ajustes de posicionamente dos gráficos
fig.update_layout(xaxis_rangeslider_visible=False,
                  xaxis=dict(zerolinecolor='black', showticklabels=False),
                  xaxis2=dict(showticklabels=False))
fig['layout']['yaxis2'].update(range=[minimo,maximo])

fig.update_xaxes(showline=True, linewidth=1, linecolor='black', mirror=False)
fig.show()